[package]
name = "meic_mq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "2.3.0"
serde = "1.0.145"
zmq = "0.9.2"
